version: '3.8'
services:
  postgres-user-preference:
    image: postgres:13
    environment:
      POSTGRES_DB: user-preference-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres-user-preference-data:/var/lib/postgresql/data

  postgres-template:
    image: postgres:13
    environment:
      POSTGRES_DB: template-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres-template-data:/var/lib/postgresql/data

  postgres-tracking:
    image: postgres:13
    environment:
      POSTGRES_DB: tracking-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres-tracking-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  user-preference-service:
    build:
      context: ./user-preference-service
      dockerfile: Dockerfile
    depends_on:
      - postgres-user-preference
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user-preference:5432/user-preference-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  template-service:
    build:
      context: ./template-service
      dockerfile: Dockerfile
    depends_on:
      - postgres-template
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-template:5432/template-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  event-processor-service:
    build:
      context: ./event-processor-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    ports:
      - "8083:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  orchestrator-service:
    build:
      context: ./orchestrator-service
      dockerfile: Dockerfile
    ports:
      - "8084:8080"

  dispatcher-service:
    build:
      context: ./dispatcher-service
      dockerfile: Dockerfile
    ports:
      - "8085:8080"

  tracking-service:
    build:
      context: ./tracking-service
      dockerfile: Dockerfile
    depends_on:
      - postgres-tracking
    ports:
      - "8086:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-tracking:5432/tracking-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
  
  notification-api-gateway:
    build:
      context: ./notification-api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      USER_PREFERENCE_SERVICE_URL: http://user-preference-service:8081
      TEMPLATE_SERVICE_URL: http://template-service:8082
      ORCHESTRATOR_SERVICE_URL: http://orchestrator-service:8084
      TRACKING_SERVICE_URL: http://tracking-service:8086

volumes:
  postgres-user-preference-data:
  postgres-template-data:
  postgres-tracking-data:
