apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tracking-service
  template:
    metadata:
      labels:
        app: tracking-service
    spec:
      containers:
        - name: tracking-service
          image: <dockerhub-user>/tracking-service:<tag>
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: tracking-service-config