
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [
          'user-preference-service:8080',
          'template-service:8080',
          'event-processor-service:8080',
          'orchestrator-service:8080',
          'dispatcher-service:8080',
          'tracking-service:8080',
          'notification-api-gateway:8080'
        ]
