apiVersion: v1
kind: Service
metadata:
  name: event-processor-service
spec:
  selector:
    app: event-processor-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP