apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    metadata:
      labels:
        app: dispatcher-service
    spec:
      containers:
        - name: dispatcher-service
          image: <dockerhub-user>/dispatcher-service:<tag>
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: dispatcher-service-config