apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: template-service
  template:
    metadata:
      labels:
        app: template-service
    spec:
      containers:
        - name: template-service
          image: <dockerhub-user>/template-service:<tag>
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: template-service-config